mongo = new Mongo("localhost");
mydb = mongo.getDB("RedMedal");
friends = mydb.getCollection("friends");
friends.insertMany([{
        uuid: '08c0a6ec-',
        title: '培训中心web讲师',
        price: '10-15K',
        company: '瑞轩科技',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '2-5年',
        education: '本科',
        technology1: '前端',
        technology2: 'Vue',
        technology3: 'nodejs',
        avatar: '/images/head/head1.png',
        name: '黄雅婕',
        password: "666",
        region: '天津',
        latitude: 39.071537,
        longitude: 117.109671,
        content: '岗位职责：\n1.负责前端框架设计与功能开发\n2.优化代码，提升页面响应速度及交互体验。\n3.参与前端组件库、基础架构、微前端架构设计与维护；\n4.理解并结合需求，以优质用户体验为目标，持续优化迭代，为用户提供稳定高效的平台；\n任职资格：\n1.3年以上前端开发经验，熟练掌握HTML5、JavaScript、CSS3、DOM等基本WEB开发技术；\n2.对主流图表库（Echarts \ Chartsjs \ G2 \ Gojs \ D3js等）至少一种有深入应用并深入理解其设计原理；\n3.对主流前端框架（React\Vue\Angular等）至少一种有深入应用并深入理解其设计原理；\n4.熟练应用webpack打包工具，熟练应用ES6语法，熟练npm包管理工具、熟练git操作，多分支管理；\n5.熟悉微前端架构设计（加分项）\n6.熟悉B/S模式下复杂报表开发（加分项）\n7.熟悉egg、koa2、express等node.js框架开发(加分项)\n8.较好的产品意识，对用户需求、体验、交互、操作流程等有一定追求；\n9.积极乐观，责任心强，工作认真细致，具备良好的编码规范和服务意识，具有良好的团队沟通与协作能力。\n公司介绍\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n'
    },
    {
        uuid: '3bb179af-b',
        title: '前端工程师',
        price: '5-15K',
        company: '瑞轩科技',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '3-10年',
        education: '本科',
        technology1: '前端',
        technology2: 'Vue',
        technology3: 'nodejs',
        avatar: '/images/head/head2.png',
        name: '刘颖娜',
        password: "666",
        region: '河北',
        latitude: 39.071537,
        longitude: 117.109671,
        content: '岗位职责：\n1.负责前端框架设计与功能开发\n2.优化代码，提升页面响应速度及交互体验。\n3.参与前端组件库、基础架构、微前端架构设计与维护；\n4.理解并结合需求，以优质用户体验为目标，持续优化迭代，为用户提供稳定高效的平台；\n任职资格：\n1.3年以上前端开发经验，熟练掌握HTML5、JavaScript、CSS3、DOM等基本WEB开发技术；\n2.对主流图表库（Echarts \ Chartsjs \ G2 \ Gojs \ D3js等）至少一种有深入应用并深入理解其设计原理；\n3.对主流前端框架（React\Vue\Angular等）至少一种有深入应用并深入理解其设计原理；\n4.熟练应用webpack打包工具，熟练应用ES6语法，熟练npm包管理工具、熟练git操作，多分支管理；\n5.熟悉微前端架构设计（加分项）\n6.熟悉B/S模式下复杂报表开发（加分项）\n7.熟悉egg、koa2、express等node.js框架开发(加分项)\n8.较好的产品意识，对用户需求、体验、交互、操作流程等有一定追求；\n9.积极乐观，责任心强，工作认真细致，具备良好的编码规范和服务意识，具有良好的团队沟通与协作能力。\n公司介绍\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n'
    },
    {
        uuid: 'fdee46b0-4b0',
        title: 'web工程师',
        price: '10-20K',
        company: '天软实习',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '2-3年',
        education: '本科',
        technology1: '前端',
        technology2: 'vue',
        technology3: 'nodejs',
        avatar: '/images/head/head3.png',
        name: '路嘉强',
        password: "666",
        latitude: 39.071537,
        longitude: 117.109671,
        region: '北京',
        content: '岗位职责：\n1、根据需求分析文档完成数据库及程序设计；\n2、制定开发计划并能够分析解决软件开发过程中的问题。\n任职要求：\n1、计算机相关专业全日制本科及以上学历，211，985院校优先，4年以上Java工作经验；\n2、熟练应用多种JAVA设计模式，并在实际的项目中有比较丰富的应用经验；\n3、精通J2EE相关技术，精通spring mvc、mybatis、spring、dubbo等开源技术框架；\n4、掌握MySQL数据库的开发、配置、管理、调试，熟练掌握SQL查询优化；\n5、熟练使用svn、git等版本管理工具；\n6、有大型互联网公司经验或大型分布式系统开发经验者优先，熟悉分布式消息队列（RabbitMQ、RocketMQ等），分布式缓存（Redis、Memcached），zookeeper等；\n7、强烈的责任心和良好的分析问题、解决问题的能力，良好的沟通能力，良好的职业道德及敬业精神。'
    },
    {
        uuid: '003',
        title: '中高级程师',
        price: '15-25K',
        company: '天地伟业技术有限公司',
        NumberP: '99-200人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: 'J2EE',
        technology2: 'spring',
        technology3: 'svn',
        avatar: '/images/head/head4.png',
        name: '李成',
        password: "666",
        latitude: 33.071537,
        longitude: 119.109671,
        region: '天津',
        content: '工作职责 \n1.作为研发骨干可以独立承担城市大脑、交通大脑的重点模块研发工作； \n2.承担研发层面设计、文档编写、配合测试测试工作；\n 3.支持软件产品项目上线应用；\n 4.领导交办的其他工作。 \n任职资格\n 1.985/211统招本科计算机或相关专业毕业，至少5年以上Java研发经验；\n 2.熟练掌握SpringMVC、SpringBoot、SpringCloud、MyBatis、JQuery等框架，熟悉自动单元测试框架；\n 3.熟练使用SQL、Oracle、MySQL等主流数据库，熟练掌握Java多线程编程；\n 4.具有大数据、可视化框架、时空平台相关开发、产品研发经验优先。'
    },
    {
        uuid: '33c3693b-dbb',
        title: 'Java中高级程师',
        price: '13-26K',
        company: '北京易华录信息技术股份有限公司',
        NumberP: '99-200人',
        financing: '不需要融资',
        Years: '5-10年',
        education: '本科',
        technology1: 'java',
        technology2: 'spring',
        technology3: 'springCloud',
        avatar: '/images/head/head1.png',
        name: '王先生 招聘经理',
        password: "666",
        latitude: 42.071537,
        longitude: 123.109671,
        region: '天津',
        content: '岗位职责：\n 1、根据产品设计完成云计算平台的设计与开发工作；\n 2、负责中间件服务的升级改造工作；\n 3、解决研发过程中的技术问题； 任职要求： 1、3年以上服务端开发经验，基础知识扎实； \n2、精通java常用技术栈，包括但不限于SpringBoot、SpringCloud；\n 3、研究过JVM调优、缓存、分布式系统、消息队列等技术，并有相关开发经验； \n4、做事积极主动，发现问题，解决问题，有较强的学习能力、执行能力和沟通能力；\n 5、有高性能、高并发、高可用、高扩展系统架构经验优先；\n 6、技术栈宽者优先，如python和golang的项目经验； \n7、有私有云平台实践经验；\n 8、有Kubernetes K8S+docker容器化实践经验优先；\n 9、学历:统招本科，硕士或统招211/985本科优先'
    },
    {
        uuid: '005',
        title: '系统架构师',
        price: '20-35K',
        company: '神州尚龙',
        NumberP: '99-200人',
        financing: '不需要融资',
        Years: '5-10年',
        education: '本科',
        technology1: 'SpringMVC',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head4.png',
        name: '李女士 招聘经理',
        password: "666",
        latitude: 41.071537,
        longitude: 146.109671,
        region: '天津',
        content: '1、性别不限，计算机相关专业本科及以上学历，5年以上软件工作经验；\n 2、精通常用设计模式和主流设计工具，具有Java框架设计能力，有搭建Java框架经验，能承担核心模块的开发，能根据既定产品和项目的特性进行技术架构设计；\n 3、深入了解SpringMVC、Spring、MyBatis、Redis、Zookeeper等框架（框架提供的特性及其实现原理）； \n4、熟悉多线程与NIO编程，熟悉常用数据结构和算法；\n 5、具备业界主流大数据、高并发、高性能架构经验；\n 6、熟悉jvm内存管理和jvm调优，熟悉缓存技术，网站优化，服务器优化，集群技术处理、网站负载均衡、系统性能调优等软件编程高级技术； \n7、具备良好的文档撰写能力和沟通能力；\n 8、具备海量数据、高并发、高性能分析及处理、分布式系统(互联网经验)能力的优先。'
    },
    {
        uuid: '006',
        title: '系统架构师',
        price: '20-35K',
        company: '神州尚龙',
        NumberP: '99-200人',
        financing: '不需要融资',
        Years: '5-10年',
        education: '本科',
        technology1: 'SpringMVC',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head1.png',
        name: '田女士 招聘经理',
        password: "666",
        latitude: 37.071537,
        longitude: 123.109671,
        region: '天津',
        content: '1、性别不限，计算机相关专业本科及以上学历，5年以上软件工作经验；\n 2、精通常用设计模式和主流设计工具，具有Java框架设计能力，有搭建Java框架经验，能承担核心模块的开发，能根据既定产品和项目的特性进行技术架构设计；\n 3、深入了解SpringMVC、Spring、MyBatis、Redis、Zookeeper等框架（框架提供的特性及其实现原理）； \n4、熟悉多线程与NIO编程，熟悉常用数据结构和算法；\n 5、具备业界主流大数据、高并发、高性能架构经验；\n 6、熟悉jvm内存管理和jvm调优，熟悉缓存技术，网站优化，服务器优化，集群技术处理、网站负载均衡、系统性能调优等软件编程高级技术； \n7、具备良好的文档撰写能力和沟通能力；\n 8、具备海量数据、高并发、高性能分析及处理、分布式系统(互联网经验)能力的优先。'
    },
    {
        uuid: '007',
        title: 'Java开发工程师',
        price: '15-25K',
        company: '天士力控股集团',
        NumberP: '99-200人',
        financing: '上市',
        Years: '5-10年',
        education: '本科',
        technology1: 'SpringMVC',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head3.png',
        name: '赵先生 招聘经理',
        password: "666",
        latitude: 34.071537,
        longitude: 124.109671,
        region: '天津',
        content: '岗位职责:\n 1、对集团所属自开发架构应用系统集成进行方案评估。\n 2、按用例进行需求分析和技术方案设计。\n 3、进行软件详细设计和编码实现，确保性能、质量和安全。\n 4、对业务系统进行运维支持。 \n任职资格:\n 1、 扎实的java编程基础， 熟悉Spring、Spring Boot、Spring Cloud等框架。\n 2、 熟悉 Spring Cloud微服务架构，有深入阅读 Spring Cloud 源代码、Spring Boot 源代码优先。\n 3、 熟悉 HTTP、Restful API，有参与过大规模微服务项目的经验。\n 4、 熟悉云原生技术，包括DevOps，Kubernetes等。\n 5、 具备良好的团队合作能力，具备良好的工作热情和责任感。'
    },
    {
        uuid: '008',
        title: 'Java',
        price: '15-30K',
        company: '恒安嘉新',
        NumberP: '1000-3000人',
        financing: '上市',
        Years: '5-10年',
        education: '本科',
        technology1: 'SpringMVC',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head1.png',
        name: '石女士 平台研发经理',
        password: "666",
        latitude: 40.071537,
        longitude: 112.109671,
        region: '天津',
        content: '1、根据项目要求完成模块详细设计和编程实现 \n2、负责相关服务模块开发及性能改进，在性能和稳定性上达到需求 \n3、负责系统框架和核心代码开发 \n4、按照设计要求及源代码编写规范编写程序代码，并编写相关技术文档，对其质量、性能负责 \n5、完成其他工作相关的临时性工作 '
    },
    {
        uuid: '009',
        title: 'c',
        price: '12-24K',
        company: '大宇宙创造有限公司',
        NumberP: '500-990人',
        financing: '不需要融资',
        Years: '5-10年',
        education: '大专',
        technology1: 'Mysql',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head4.png',
        name: '于先生 人事',
        password: "666",
        latitude: 32.071537,
        longitude: 119.109671,
        region: '天津',
        content: '1、具备丰富的教学经验，优秀的课堂组织能力，优秀的表达能力以及课堂的把控能力\n 2、精通Java编程思想，5年以上Java开发经验，有微服务实战开发者优先\n 3、具备大中型项目的系统架构及系统研发能力，只要从事过2个以上的项目实战开发 \n4、熟悉Mysql、Oracle、MongoDB等常用的存储技术，熟悉PowerDesigner数据库设计工具 \n5、熟悉Spring、SpringMVC、Mybatis、WebFlux、Lucene、ElasticSearch等常用技术的应用 \n6、熟悉Spring Cloud、Dubbo、Kubernetes等主流的微服务技术。 \n7、熟悉使用MD软件编写技术文档，具备良好的文档编写习惯和代码书写规范。\n 8、有很强的责任心，深刻理解IT教育培训的核心思想'
    },
    {
        uuid: '010',
        title: 'java软件工程师',
        price: '12-22K',
        company: '宇信科技',
        NumberP: '500-990人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: 'Mysql',
        technology2: 'Spring',
        technology3: 'Redis',
        avatar: '/images/head/head3.png',
        name: '文先生 部门经理',
        password: "666",
        latitude: 38.071537,
        longitude: 120.109671,
        region: '北京',
        content: '1.本科及以上学历，计算机相关专业，有金融科技相关工作经验优先； \n2.Java基础扎实；熟悉多线程编程，熟悉分布式、缓存、消息队列等机制，熟悉JVM机制； 3.理解相关开源框架的原理和机制，包括但不限于Spring/SpringBoot等；\n 3.熟悉基于Mysql的设计和开发，熟练进行Linux系统操作、git操作，能独立完成部署及基本服务器运维操作；\n 4.技术视野开阔，学习能力好，具有良好的编码习惯，良好的人际沟通能力，良好的工作协调能力； \n5.有分布式、高并发、高负载、高可用性系统设计和稳定性经验优先； \n6.服务相关开发及数据治理经验优先；'
    },
    {
        uuid: '011',
        title: 'java软件工程师',
        price: '12-22K',
        company: '宇信科技',
        NumberP: '500-990人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: 'ISCSI',
        technology2: 'Hadoop',
        technology3: 'NAS',
        avatar: '/images/head/head1.png',
        name: '杨女士 存储研发二部部门经理',
        password: "666",
        latitude: 42.071537,
        longitude: 127.109671,
        region: '天津',
        content: '1.负责分布式存储系统功能管理模块后台功能设计及开发。\n 2.负责分布式存储系统软硬件智能运维故障预测等相关后台功能设计及开发。 \n3.参与NAS（NFS/SMB/FTP），ISCSI，Hadoop，S3等协议实现的研发相关设计和功能维护。\n 4.参与zookeeper，rocksdb等开源工具的深入维护。\n 5.参与模块框架和代码架构的持续优化改进。参与团队的code review，确保代码正确性及可维护性。 \n岗位要求\n 1. 计算机、通信、电子等相关专业本科及以上学历。3年及其以上Java研发工作经验。 \n2.扎实的Java语言编码调试能力，熟练使用各种典型数据结构，对面向对象和设计模式有深入的理解。有良好的计算机基础，熟悉计算机组成原理、体系结构、网络、操作系统等相关知识。 \n3.对部分 Java 技术（如zookeeper，Mysql, Redis, rocketMq，spring）有深入研究，研究过优秀开源软件的源码并有心得者优先。 \n4.具有大型分布式、高并发、高负载、高可用性系统设计开发经验者优先。\n 5.有良好的设计文档，操作文档，开发文档编写能力。 \n6.有责任心，有主动性，有团队合作精神，沟通能力强，抗压能力强。'
    },
    {
        uuid: 'sdfasdfsadf',
        title: '前端工程师',
        price: '10-15K',
        company: '瑞轩科技',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: '前端',
        technology2: 'Vue',
        technology3: 'nodejs',
        avatar: '/images/head/head3.png',
        name: '白先生 人力资源主管',
        region: '天津',
        latitude: 39.071537,
        longitude: 117.109671,
        content: '岗位职责：\n1.负责前端框架设计与功能开发\n2.优化代码，提升页面响应速度及交互体验。\n3.参与前端组件库、基础架构、微前端架构设计与维护；\n4.理解并结合需求，以优质用户体验为目标，持续优化迭代，为用户提供稳定高效的平台；\n任职资格：\n1.3年以上前端开发经验，熟练掌握HTML5、JavaScript、CSS3、DOM等基本WEB开发技术；\n2.对主流图表库（Echarts \ Chartsjs \ G2 \ Gojs \ D3js等）至少一种有深入应用并深入理解其设计原理；\n3.对主流前端框架（React\Vue\Angular等）至少一种有深入应用并深入理解其设计原理；\n4.熟练应用webpack打包工具，熟练应用ES6语法，熟练npm包管理工具、熟练git操作，多分支管理；\n5.熟悉微前端架构设计（加分项）\n6.熟悉B/S模式下复杂报表开发（加分项）\n7.熟悉egg、koa2、express等node.js框架开发(加分项)\n8.较好的产品意识，对用户需求、体验、交互、操作流程等有一定追求；\n9.积极乐观，责任心强，工作认真细致，具备良好的编码规范和服务意识，具有良好的团队沟通与协作能力。\n公司介绍\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n'
    },
    {
        uuid: 'rgregagagadrr4434',
        title: '前端工程师',
        price: '10-15K',
        company: '瑞轩科技',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: '前端',
        technology2: 'Vue',
        technology3: 'nodejs',
        avatar: '/images/head/head4.png',
        name: '牛先生 人力资源主管',
        name: '天津',
        latitude: 39.071537,
        longitude: 117.109671,
        content: '岗位职责：\n1.负责前端框架设计与功能开发\n2.优化代码，提升页面响应速度及交互体验。\n3.参与前端组件库、基础架构、微前端架构设计与维护；\n4.理解并结合需求，以优质用户体验为目标，持续优化迭代，为用户提供稳定高效的平台；\n任职资格：\n1.3年以上前端开发经验，熟练掌握HTML5、JavaScript、CSS3、DOM等基本WEB开发技术；\n2.对主流图表库（Echarts \ Chartsjs \ G2 \ Gojs \ D3js等）至少一种有深入应用并深入理解其设计原理；\n3.对主流前端框架（React\Vue\Angular等）至少一种有深入应用并深入理解其设计原理；\n4.熟练应用webpack打包工具，熟练应用ES6语法，熟练npm包管理工具、熟练git操作，多分支管理；\n5.熟悉微前端架构设计（加分项）\n6.熟悉B/S模式下复杂报表开发（加分项）\n7.熟悉egg、koa2、express等node.js框架开发(加分项)\n8.较好的产品意识，对用户需求、体验、交互、操作流程等有一定追求；\n9.积极乐观，责任心强，工作认真细致，具备良好的编码规范和服务意识，具有良好的团队沟通与协作能力。\n公司介绍\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n北京千方科技股份有限公司（简称“千方科技”，股票代码002373）深耕中国智慧交通领域近二十载，业务覆盖智能基础设施、智慧路网、智慧航港、汽车电子、智慧城市•交通脑等行业前沿领域，形成从产品到解决方案、从云端数据到出行者、从硬件基础设施到软件智慧中枢的完整产业链条，\n'
    },
    {
        uuid: '3434tt43',
        title: '前端工程师',
        price: '10-15K',
        company: '天软实习',
        NumberP: '0-20人',
        financing: '不需要融资',
        Years: '2-3年',
        education: '本科',
        technology1: '前端',
        technology2: 'vue',
        technology3: 'nodejs',
        avatar: '/images/head/head1.png',
        name: '周先生 HRBP',
        latitude: 39.071537,
        longitude: 117.109671,
        region: '天津',
        content: '岗位职责：\n1、根据需求分析文档完成数据库及程序设计；\n2、制定开发计划并能够分析解决软件开发过程中的问题。\n任职要求：\n1、计算机相关专业全日制本科及以上学历，211，985院校优先，4年以上Java工作经验；\n2、熟练应用多种JAVA设计模式，并在实际的项目中有比较丰富的应用经验；\n3、精通J2EE相关技术，精通spring mvc、mybatis、spring、dubbo等开源技术框架；\n4、掌握MySQL数据库的开发、配置、管理、调试，熟练掌握SQL查询优化；\n5、熟练使用svn、git等版本管理工具；\n6、有大型互联网公司经验或大型分布式系统开发经验者优先，熟悉分布式消息队列（RabbitMQ、RocketMQ等），分布式缓存（Redis、Memcached），zookeeper等；\n7、强烈的责任心和良好的分析问题、解决问题的能力，良好的沟通能力，良好的职业道德及敬业精神。'
    },
    {
        uuid: 'errgr44',
        title: '中高级程师',
        price: '15-25K',
        company: '天地伟业技术有限公司',
        NumberP: '99-200人',
        financing: '不需要融资',
        Years: '1-3年',
        education: '本科',
        technology1: 'J2EE',
        technology2: 'spring',
        technology3: 'svn',
        avatar: '/images/head/head3.png',
        name: '王先生 人力资源主管',
        latitude: 33.071537,
        longitude: 119.109671,
        region: '天津',
        content: '工作职责 \n1.作为研发骨干可以独立承担城市大脑、交通大脑的重点模块研发工作； \n2.承担研发层面设计、文档编写、配合测试测试工作；\n 3.支持软件产品项目上线应用；\n 4.领导交办的其他工作。 \n任职资格\n 1.985/211统招本科计算机或相关专业毕业，至少5年以上Java研发经验；\n 2.熟练掌握SpringMVC、SpringBoot、SpringCloud、MyBatis、JQuery等框架，熟悉自动单元测试框架；\n 3.熟练使用SQL、Oracle、MySQL等主流数据库，熟练掌握Java多线程编程；\n 4.具有大数据、可视化框架、时空平台相关开发、产品研发经验优先。'
    }
])